//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMovieRegister
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public int id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string length { get; set; }
        public string year { get; set; }
        public string genre { get; set; }
        public bool hasSeen { get; set; }
        public bool isFavourite { get; set; }
        public string posterUrl { get; set; }
    }
}
